import { prisma } from '@/lib/db'
import { ok, err, requireAuth, scopeFilter } from '@/lib/api'
import { computePayrollFromNet } from '@/lib/utils'
import { NextRequest } from 'next/server'

export async function POST(req: NextRequest) {
  try {
    const session = await requireAuth()
    if (session.user?.role === 'operator') return err('Accès refusé', 403)
    const scope = scopeFilter(session)
    const body = await req.json()
    const { period, create = false } = body
    if (!period) return err('Période requise', 400)

    const missions = await prisma.mission.findMany({
      where: { ...scope, status: 'active' },
      include: {
        candidate: { select: { firstName: true, lastName: true } },
        client: { select: { id: true, name: true, paymentTermsDays: true, commissionRate: true } },
        country: {
          include: { contributions: true, irsaBrackets: true },
        },
        attendance: { where: { period, status: 'validated' } },
      },
    })

    if (missions.length === 0) return ok([])

    const existingInvoices = await prisma.invoice.findMany({
      where: { ...scope, period, autoGenerated: true },
      select: { clientId: true, invoiceType: true },
    })
    const existingKeys = new Set(existingInvoices.map(e => `${e.clientId}-${e.invoiceType}`))

    const groups = new Map<string, typeof missions>()
    for (const m of missions) {
      const key = `${m.countryId}-${m.clientId}-${m.contractType}`
      if (!groups.has(key)) groups.set(key, [])
      groups.get(key)!.push(m)
    }

    const overtimeRecords = await prisma.overtimeRecord.findMany({
      where: {
        missionId: { in: missions.map(m => m.id) },
        status: 'validated',
        invoiceLineId: null,
        date: { gte: new Date(`${period}-01`), lt: new Date(`${period}-31`) },
      },
      select: { id: true, missionId: true, amount: true, hours: true },
    })
    const overtimeByMission = new Map<number, { amount: number; hours: number; ids: number[] }>()
    for (const o of overtimeRecords) {
      const cur = overtimeByMission.get(o.missionId) ?? { amount: 0, hours: 0, ids: [] }
      cur.amount += o.amount
      cur.hours += o.hours
      cur.ids.push(o.id)
      overtimeByMission.set(o.missionId, cur)
    }

    const previews: any[] = []

    for (const [, groupMissions] of groups) {
      const first = groupMissions[0]
      const groupKey = `${first.clientId}-${first.contractType}`
      if (existingKeys.has(groupKey)) continue

      const [y, m] = period.split('-').map(Number)
      const periodDate = new Date(y, m - 1, 1)
      const dueDate = new Date(periodDate)
      dueDate.setDate(dueDate.getDate() + (first.client.paymentTermsDays ?? 30))

      const lines = groupMissions.flatMap(mission => {
        const att = mission.attendance[0]
        const daysWorked = att?.daysWorked ?? mission.prorataBase
        const prorataCoef = daysWorked / (mission.prorataBase || 30)
        const cand = `${mission.candidate.firstName} ${mission.candidate.lastName}`

        let unitPrice = 0
        let description = ''

        if (mission.contractType === 'placement') {
          unitPrice = Math.round((mission.clientRate || mission.employeeRate || 0) * prorataCoef)
          description = `Placement — ${cand}`
        } else {
          const result = computePayrollFromNet(mission.netSalary, mission.country as any, { prorataCoef })
          const massSal = result.massSalariale ?? 0
          const commRate = mission.commissionRate ?? first.client.commissionRate ?? 12
          const commission = Math.round(massSal * commRate / 100)
          unitPrice = massSal + commission
          description = `Mise à disposition — ${cand} (${daysWorked}j/${mission.prorataBase}j)`
        }

        const missionLines: any[] = [{
          missionId: mission.id,
          candidateId: mission.candidateId,
          description,
          quantity: 1,
          unitPrice: Math.round(unitPrice),
          totalHT: Math.round(unitPrice),
          daysWorked,
          prorataCoef,
        }]

        const overtime = overtimeByMission.get(mission.id)
        if (overtime && overtime.amount > 0) {
          missionLines.push({
            missionId: mission.id,
            candidateId: mission.candidateId,
            description: `Heures sup. — ${cand} (${overtime.hours}h, ${period})`,
            quantity: 1,
            unitPrice: Math.round(overtime.amount),
            totalHT: Math.round(overtime.amount),
            daysWorked: null,
            prorataCoef: null,
            overtimeRecordIds: overtime.ids,
          })
        }

        return missionLines
      })

      const subtotalHT = lines.reduce((s, l) => s + l.totalHT, 0)
      const vatRate = first.country.vatRate ?? 20
      const vatAmount = Math.round(subtotalHT * vatRate / 100)

      previews.push({
        countryId: first.countryId,
        clientId: first.clientId,
        clientName: first.client.name,
        invoiceType: first.contractType,
        date: periodDate.toISOString().slice(0, 10),
        dueDate: dueDate.toISOString().slice(0, 10),
        period,
        status: 'draft',
        subtotalHT,
        vatRate,
        vatAmount,
        syntheticTax: 0,
        total: subtotalHT + vatAmount,
        autoGenerated: true,
        notes: null,
        paymentMethod: null,
        lines,
        symbol: first.country.symbol,
      })
    }

    if (!create) return ok(previews)

    const created = []
    for (const preview of previews) {
      const { lines, clientName, symbol, ...invoiceData } = preview
      const country = await prisma.country.findUnique({ where: { id: invoiceData.countryId } })
      const invoiceYear = invoiceData.date ? new Date(invoiceData.date).getFullYear() : new Date().getFullYear()
      const count = await prisma.invoice.count({
        where: {
          countryId: invoiceData.countryId,
          date: { gte: new Date(invoiceYear, 0, 1), lt: new Date(invoiceYear + 1, 0, 1) },
        },
      })
      const reference = `${country?.invoicePrefix ?? 'INV'}-${invoiceYear}-${String(count + 1).padStart(4, '0')}`

      const linesInput = lines.map((l: any) => {
        const { overtimeRecordIds, ...rest } = l
        return rest
      })

      const invoice = await prisma.invoice.create({
        data: { ...invoiceData, reference, lines: { create: linesInput } },
        include: { lines: { orderBy: { id: 'asc' } } },
      })

      await Promise.all(
        lines.flatMap((l: any, i: number) =>
          (l.overtimeRecordIds ?? []).map((oid: number) =>
            prisma.overtimeRecord.update({ where: { id: oid }, data: { invoiceLineId: invoice.lines[i].id } })
          )
        )
      )

      created.push(invoice)
    }

    return ok(created)
  } catch (e: any) {
    if (e.message === 'UNAUTHORIZED') return err('Non autorisé', 401)
    return err(e.message ?? 'Erreur serveur', 500)
  }
}
