'use client'
import { useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { PageHeader, SearchBox, Btn, Card, Table, StatusBadge, Badge, FilterSelect } from '@/components/ui'
import { useAppStore } from '@/store/app'
import { fmt, fmtDate } from '@/lib/utils'
import { Plus } from 'lucide-react'

const STATUS_OPTS = [
  { value: 'all', label: 'Tous statuts' }, { value: 'draft', label: 'Brouillon' },
  { value: 'sent', label: 'Émise' }, { value: 'partially_paid', label: 'Partiellement payée' },
  { value: 'paid', label: 'Payée' }, { value: 'overdue', label: 'En retard' },
]
const TYPE_OPTS = [
  { value: 'all', label: 'Tous types' },
  { value: 'placement', label: 'Placement' },
  { value: 'mise_a_disposition', label: 'Mise à disposition' },
]

export function InvoicesPage() {
  const B = process.env.NEXT_PUBLIC_APP_URL ?? ''
  const [search, setSearch] = useState('')
  const [statusF, setStatusF] = useState('all')
  const [typeF, setTypeF] = useState('all')

  const { data, isLoading } = useQuery({
    queryKey: ['invoices', statusF, typeF],
    queryFn: () => fetch(`${B}/api/invoices?status=${statusF === 'all' ? '' : statusF}&type=${typeF === 'all' ? '' : typeF}`).then(r => r.json()),
  })
  const invoices = (data?.data ?? []).filter((i: any) =>
    !search || `${i.reference} ${i.client?.name}`.toLowerCase().includes(search.toLowerCase())
  )

  const cols = [
    { key: 'ref', label: 'Référence', render: (r: any) => (
      <div className="flex items-center gap-2">
        <span className="font-mono font-bold text-xs">{r.reference}</span>
        {r.autoGenerated && <Badge color="#7C3AED">AUTO</Badge>}
      </div>
    )},
    { key: 'date', label: 'Date', render: (r: any) => fmtDate(r.date) },
    { key: 'client', label: 'Client', render: (r: any) => r.client?.name ?? '—' },
    { key: 'type', label: 'Type', render: (r: any) => <Badge color={r.invoiceType === 'placement' ? '#3B82F6' : '#7C3AED'}>{r.invoiceType === 'placement' ? 'Placement' : 'MAD'}</Badge> },
    { key: 'total', label: 'Total', align: 'right' as const, render: (r: any) => <strong>{fmt(r.total, r.country?.symbol)}</strong> },
    { key: 'due', label: 'Échéance', render: (r: any) => {
      const isLate = r.status !== 'paid' && r.dueDate && new Date(r.dueDate) < new Date()
      return <span className={isLate ? 'text-red-600 font-semibold' : ''}>{fmtDate(r.dueDate)}</span>
    }},
    { key: 'status', label: 'Statut', render: (r: any) => <StatusBadge status={r.status} /> },
  ]

  return (
    <div className="fade-in space-y-4">
      <PageHeader title="Factures" subtitle={`${invoices.length} facture(s)`}
        actions={<>
          <SearchBox value={search} onChange={setSearch} />
          <FilterSelect value={statusF} onChange={setStatusF} options={STATUS_OPTS} />
          <FilterSelect value={typeF} onChange={setTypeF} options={TYPE_OPTS} />
          <Btn icon={<Plus size={14} />}>Nouvelle facture</Btn>
        </>}
      />
      <Card noPad>
        <Table columns={cols} data={invoices} empty={isLoading ? 'Chargement...' : 'Aucune facture'} />
      </Card>
    </div>
  )
}
