import { prisma } from '@/lib/db'
import { ok, err, requireAuth, scopeFilter, logAudit } from '@/lib/api'
import { NextRequest } from 'next/server'
import { computePayrollFromNet } from '@/lib/utils'

export async function GET(req: NextRequest) {
  try {
    const session = await requireAuth()
    const scope = scopeFilter(session, req)
    const { searchParams } = new URL(req.url)
    const status = searchParams.get('status') ?? ''
    const period = searchParams.get('period') ?? ''

    const payrolls = await prisma.payroll.findMany({
      where: { ...scope, ...(status && { status }), ...(period && { period }) },
      include: {
        candidate: { select: { firstName: true, lastName: true } },
        mission: { select: { contractType: true, clientId: true } },
        country: { select: { name: true, symbol: true } },
      },
      orderBy: [{ period: 'desc' }, { id: 'desc' }],
    })
    return ok(payrolls)
  } catch (e: any) {
    if (e.message === 'UNAUTHORIZED') return err('Non autorisé', 401)
    return err('Erreur serveur', 500)
  }
}

export async function POST(req: NextRequest) {
  try {
    const session = await requireAuth()
    const body = await req.json()

    const country = await prisma.country.findUnique({
      where: { id: body.countryId },
      include: { contributions: true, irsaBrackets: true },
    })
    if (!country) return err('Pays introuvable', 404)

    const attendance = await prisma.attendanceRecord.findFirst({
      where: { missionId: body.missionId, period: body.period, status: 'validated' },
    })

    const daysWorked = body.daysWorked ?? attendance?.daysWorked ?? body.prorataBase
    const prorataCoef = daysWorked / body.prorataBase

    const overtime = await prisma.overtimeRecord.aggregate({
      where: { missionId: body.missionId, status: 'validated',
        date: { gte: new Date(`${body.period}-01`), lt: new Date(`${body.period}-31`) } },
      _sum: { amount: true },
    })

    const advances = await prisma.advance.aggregate({
      where: { candidateId: body.candidateId, status: 'approved', payrollId: null },
      _sum: { amount: true },
    })

    const result = computePayrollFromNet(body.netTarget, country as any, {
      prorataCoef,
      overtimeAmount: overtime._sum.amount ?? 0,
      advances: advances._sum.amount ?? 0,
    })

    const payroll = await prisma.payroll.create({
      data: {
        countryId: body.countryId,
        candidateId: body.candidateId,
        missionId: body.missionId,
        period: body.period,
        contractType: body.contractType,
        daysWorked,
        prorataBase: body.prorataBase,
        prorataCoef,
        netTarget: body.netTarget,
        gross: result.gross,
        totalEmpCotis: result.totalEmpCotis,
        totalEmprCotis: result.totalEmprCotis,
        irsa: result.irsa,
        netBase: result.netBase,
        overtimeAmount: result.overtimeAmount,
        bonuses: body.bonuses ?? 0,
        deductions: result.advances,
        netSalary: result.netToPay,
        massSalariale: result.massSalariale,
        cotisationsJson: { employee: result.employeeContribs, employer: result.employerContribs },
        status: 'pending_validation',
        autoGenerated: body.autoGenerated ?? false,
      },
    })

    // Lier les avances utilisées
    if (advances._sum.amount && advances._sum.amount > 0) {
      await prisma.advance.updateMany({
        where: { candidateId: body.candidateId, status: 'approved', payrollId: null },
        data: { payrollId: payroll.id },
      })
    }

    void logAudit(Number(session.user?.id), 'Création', 'Bulletins', payroll.id)
    return ok(payroll, 201)
  } catch (e: any) {
    if (e.message === 'UNAUTHORIZED') return err('Non autorisé', 401)
    return err(e.message ?? 'Erreur serveur', 500)
  }
}
